# Generated by Django 5.0.2 on 2024-02-13 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friends",
            old_name="Друг",
            new_name="friend",
        ),
        migrations.RenameField(
            model_name="friends",
            old_name="Пользователь",
            new_name="user",
        ),
    ]
