# Generated by Django 5.0.2 on 2024-02-13 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_myuser_дата_рождения_remove_myuser_пол"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="Дата рождения",
            field=models.DateField(
                default=datetime.datetime(2024, 2, 13, 8, 22, 54, 427557)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myuser",
            name="Пол",
            field=models.CharField(
                choices=[("М", "Мужской"), ("Ж", "Женский")], default="М", max_length=1
            ),
            preserve_default=False,
        ),
    ]
