# Generated by Django 5.0.2 on 2024-02-13 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_myuser_дата_рождения_myuser_пол"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
