# Generated by Django 5.0.2 on 2024-02-13 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_myuser_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="Имя",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="Фамилия",
        ),
    ]
