# Generated by Django 5.0.2 on 2024-02-13 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remove_myuser_имя_remove_myuser_фамилия"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="Дата рождения",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="Пол",
            field=models.CharField(
                choices=[("М", "Мужской"), ("Ж", "Женский")], default="М", max_length=1
            ),
        ),
    ]
