# Generated by Django 5.0.2 on 2024-02-13 14:12

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_myuser_дата_рождения_alter_myuser_пол"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="Время регистрации",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="Дата рождения",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="О себе",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="Пол",
        ),
        migrations.AddField(
            model_name="myuser",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="myuser",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Дата рождения"
            ),
        ),
        migrations.AddField(
            model_name="myuser",
            name="gender",
            field=models.CharField(
                choices=[("М", "Мужской"), ("Ж", "Женский")],
                default="М",
                max_length=1,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="myuser",
            name="joined_timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Время регистрации",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(max_length=32, unique=True, verbose_name="username"),
        ),
    ]
