# Generated by Django 5.0.2 on 2024-02-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_remove_myuser_время_регистрации_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="first_name",
            field=models.CharField(default="Name", max_length=50),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="last_name",
            field=models.CharField(default="No", max_length=50),
        ),
    ]
